x_res_url = "https://docs.google.com/spreadsheets/d/19VMnasgAKv06QFvW_qL-1EJjEJHTzpyOlCU2LSOl_fA/edit?usp=sharing"
y_res_url = "https://docs.google.com/spreadsheets/d/12oJjN5OyCJTZRSZd2V9dIwKL5n2eaAxLdvKh-dUeHfw/edit?usp=sharing"